version: '3'

services:
  app:
    image: faasjs/vscode
    command: sleep infinity
    tty: true
    environment:
      SECRET_REDIS_HOST: redis
    volumes:
      - ..:/root/app:delegated
      - /root/app/node_modules/

      - ~/.ssh:/root/.ssh:delegated
    depends_on:
      - pg_development
      - pg_testing1
  nginx:
    image: faasjs/nginx
    command: nginx -g "daemon off;"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:delegated
    ports:
      - 12000:8080
    depends_on:
      - app
  pg_development:
    image: postgres:alpine
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: development
      POSTGRES_HOST_AUTH_METHOD: trust
  pg_testing1:
    image: postgres:alpine
    environment:
      POSTGRES_DB: testing
      POSTGRES_USER: testing
      POSTGRES_HOST_AUTH_METHOD: trust
